language: python
sudo: false
branches:
  only:
    - master
    - staging
    - production
python:
  - 3.5
  - 3.4
env:
  - DJANGO_VERSION=1.10.5
  - DJANGO_VERSION=1.9.12
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script: python manage.py test
